ep:ACL: '/\bacl\b/i'
ep:ArmNN: '/\barmnn\b/i'
ep:CUDA: '/\bcuda\b/i'
ep:DML:
  - '/\bdirectml\b/i'
  - '/\bdml\b/i'
ep:MIGraphX: /\bmigraphx\b/i'
ep:oneDNN: '/\bonednn\b/i'
ep:OpenVINO: '/\bopen\s*vino\b/i'
ep:RockchipNPU: '/\brockchip\b/i'

