name: Add documentation issues to docs project

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@1
        with:
#          project-url: https://github.com/microsoft/onnxruntime/projects/6
          project-url: https://github.com/users/natke/projects/2
          github-token: ${{ secrets.GITHUB_TOKEN }}
          labeled: documentation
